### ISSUE TITLE
Lines vs statements

### ISSUE THREAD

**Issue by foresmac** [vokal/golang-cover-parse#3]
Here's a sample of the lines vs. statements issue:

Sample coverprofile.txt:

```
...
vip/fetch/manip.go:121.36,123.3 1 0
...
```

Here's the lines from the code:

``` go
    if png.Encode(pngBuf, raw) != nil {
        return nil, err
    }
```

So the cover profile is saying there's only one statement there, even though it covers three lines.

I believe you are translating each block into a range of lines, and then if the last number is > 0, those lines are covered, else they aren't, right?

**Comment by jrit** [comment]
Correct, 121.36,123.3 1 0 indicates lines 121-123 and the zero at the end indicates there is no coverage of those lines. Sometimes these ranges overlap lines, and in those cases if any of the lines have count > 0 then the line was hit. The prior number `1` that indicates `numberOfStatements` is ignored, even though that seems to be what Go Cover uses to calculate its own coverage percentages, it doesn't correspond to anything in LCOV.

Is there an issue, or was this just a question?

**Comment by foresmac** [comment]
Mostly a question.
